name: Generate long-term charts

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # リポジトリ名から INDEX_KEY を自動推定（共通 yaml を各 repo で使えるように）
      - name: Resolve INDEX_KEY from repository
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          REPO="${GITHUB_REPOSITORY##*/}"
          case "$REPO" in
            3_Sakura_Space) KEY="astra4" ;;
            S-COIN-)        KEY="scoin_plus" ;;
            R-BANK9)        KEY="rbank9" ;;
            AIN-10)         KEY="ain10" ;;
            *)              echo "Unknown repo '$REPO' — set KEY=index"; KEY="index" ;;
          esac
          echo "INDEX_KEY=$KEY" | tee -a "$GITHUB_ENV"
          echo "Resolved INDEX_KEY=$KEY (from repo=$REPO)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Force clear pycache
        run: rm -rf scripts/__pycache__ || true

      - name: List BEFORE
        run: |
          echo "CWD=$(pwd)"
          ls -lah
          ls -lah docs/outputs || true
          echo "Existing PNGs:"
          ls -1 docs/outputs/*.png 2>/dev/null || true

      # 日次履歴を intraday から更新（存在しない場合もエラーにしない）
      - name: Append daily history from intraday
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        run: |
          set -e
          if [ -f scripts/update_history.py ]; then
            echo "Running update_history.py (INDEX_KEY=$INDEX_KEY)"
            python scripts/update_history.py || true
          else
            echo "scripts/update_history.py not found. Skip."
          fi

      # 生成スクリプトの先頭を出力して、確実に新しいコードが走っていることをログで確認
      - name: Generate long-term charts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
          # 参考: セッション境界をコード側で持っているが、ログ目的で残しておく
          CLAMP_SESSION: "true"
          SESSION_START_JST: "09:00"
          SESSION_END_JST:   "15:30"
        run: |
          set -e
          echo "=== running long_charts.py ==="
          ls -l scripts/
          echo "--- head scripts/long_charts.py ---"
          head -n 60 scripts/long_charts.py || true
          echo "--- sample intraday (if exists) ---"
          shopt -s nullglob
          for f in docs/outputs/*_intraday.csv; do
            echo ">> $f"; head -n 5 "$f"; done || true
          echo "----------------------------------"
          python scripts/long_charts.py

      - name: List AFTER
        run: |
          echo "=== AFTER ==="
          ls -lah docs/outputs || true
          echo "Generated PNGs:"
          ls -1 docs/outputs/*.png 2>/dev/null || true
          echo "Txt markers:"
          ls -1 docs/outputs/*_post_intraday.txt 2>/dev/null || true
          echo "-- git status --"
          git status --porcelain

      - name: Commit charts if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/*.png docs/outputs/*history.csv docs/outputs/*_post_intraday.txt 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            MSG="chore(charts): update long-term charts (1d/7d/1m/1y)"
            git commit -m "$MSG"
            git push
          fi
