name: Generate long-term charts (S-COIN+)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"   # 毎日 JST 15:15 実行（任意で変更）

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # ← long_charts.py が読むキー。ファイル名と対応（scoin_plus_*.csv）
      INDEX_KEY: scoin_plus
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 事前に CSV があるかを確認（名前が違うと生成されません）
      - name: List BEFORE
        run: |
          ls -lah
          echo "---- docs/outputs ----"
          ls -lah docs/outputs || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          # 万一 requirements に含め忘れがあっても最低限動かす
          pip install pandas matplotlib pytz python-dateutil

      - name: Generate long-term charts
        run: |
          set -e
          python scripts/long_charts.py

      - name: List AFTER
        run: |
          echo "---- docs/outputs (after) ----"
          ls -lah docs/outputs || true

      # 変更がある場合のみ自動コミット
      - name: Commit charts if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(charts): update S-COIN+ long-term charts"
          file_pattern: |
            docs/outputs/scoin_plus_*.png
            docs/outputs/scoin_plus_*.csv
          push_options: --force-with-lease
