name: Generate long-term charts (S-COIN+)

on:
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * *"   # 任意。毎日JST 15:35 頃などに合わせる場合は調整

permissions:
  contents: write   # ← これが無いとコミットできません

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # ---- 必須 ----
      INDEX_KEY: scoin_plus              # 出力ファイル名の接頭辞（scoin_plus_*.png）
      PROFILE: jst_stock                 # 日本株時間 09:00-15:30 JST
      DISPLAY_TZ: Asia/Tokyo             # 軸ラベル表示
      RAW_TZ_INTRADAY: Asia/Tokyo        # intraday.csv のタイムゾーン
      RAW_TZ_HISTORY: Asia/Tokyo         # history.csv のタイムゾーン（あれば）
      # ---- 任意（無くてもOK）----
      OUT_DIR: docs/outputs              # 出力先

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas matplotlib pytz python-dateutil
          fi

      - name: Generate long-term charts (1d/7d/1m/1y)
        run: |
          set -e
          echo "::group::Run long_charts.py"
          python scripts/long_charts.py
          echo "::endgroup::"

      - name: List outputs (before commit)
        run: |
          echo "== ls -al docs/outputs =="
          ls -al docs/outputs || true

      - name: Upload artifacts (PNG/CSV)
        uses: actions/upload-artifact@v4
        with:
          name: scoin-plus-charts
          path: |
            docs/outputs/scoin_plus_*.png
            docs/outputs/*history*.csv
            docs/outputs/*intraday*.csv
          if-no-files-found: warn

      - name: Commit charts if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/*.png || true
          if git diff --cached --quiet; then
            echo "No PNG changes to commit."
          else
            git commit -m "chore(charts): update S-COIN+ long-term charts (1d/7d/1m/1y)"
            git push
          fi
