name: S-COIN+ • intraday snapshot (JST 09:00–15:30)

on:
  workflow_dispatch:
  schedule:
    # 平日 09:00–15:30 JST（= 00:00–06:30 UTC）に5分おき実行
    - cron: "*/5 0-6 * * 1-5"

permissions:
  contents: write

concurrency:
  group: scoin-plus-intraday
  cancel-in-progress: false

env:
  INDEX_KEY: scoin_plus
  OUT_DIR: docs/outputs

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python - <<'PY'
          import sys
          print("Python:", sys.version.split()[0])
          PY

      - name: Verify scripts exist
        run: |
          set -euxo pipefail
          test -f scripts/make_intraday_post.py || (echo "scripts/make_intraday_post.py NOT FOUND" && exit 2)
          ls -la ${OUT_DIR} || true

      - name: Generate intraday post & snapshot (JST session)
        run: |
          set -euxo pipefail
          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${OUT_DIR}/${INDEX_KEY}_intraday.csv" \
            --out-json "${OUT_DIR}/${INDEX_KEY}_stats.json" \
            --out-text "${OUT_DIR}/${INDEX_KEY}_post_intraday.txt" \
            --snapshot-png "${OUT_DIR}/${INDEX_KEY}_intraday.png" \
            --session "09:00-15:30" \
            --label "SCOIN_PLUS (1d)"
          echo "--- ${INDEX_KEY}_post_intraday.txt ---"
          sed -n '1,80p' "${OUT_DIR}/${INDEX_KEY}_post_intraday.txt" || true
          echo "--- ${INDEX_KEY}_stats.json ---"
          head -c 300 "${OUT_DIR}/${INDEX_KEY}_stats.json" || true

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scoin-plus-intraday
          path: |
            docs/outputs/${{ env.INDEX_KEY }}_intraday*.png
            docs/outputs/${{ env.INDEX_KEY }}_post_intraday.txt
            docs/outputs/${{ env.INDEX_KEY }}_stats.json

      - name: Commit outputs if changed
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A ${OUT_DIR}
          if ! git diff --cached --quiet; then
            git commit -m "chore(intraday): update ${INDEX_KEY} snapshot & post (JST 09:00–15:30)"
            git push
          else
            echo "No changes to commit."
          fi
