name: Run S-COIN+ intraday

permissions:
  contents: write

on:
  schedule:
    - cron: "35 6 * * *"   # 毎日 15:35 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Run S-COIN+ intraday
        run: python src/scoin_plus_intraday.py
      - name: Commit and push outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/outputs/*
          if ! git diff --cached --quiet; then
            git commit -m "Update S-COIN+ intraday snapshot"
            git push
          fi
