name: Update S-COIN+ Intraday Snapshot

on:
  schedule:
    # ▶ 前場終了後（11:35 JST = 02:35 UTC）
    - cron: '35 2 * * 1-5'
    # ▶ 後場終了後（15:35 JST = 06:35 UTC）
    - cron: '35 6 * * 1-5'
  workflow_dispatch:  # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify scripts & inputs exist
        run: |
          test -f scripts/make_intraday_post.py
          test -f docs/outputs/scoin_plus_intraday.csv

      - name: Generate intraday post and snapshot
        run: |
          set -euxo pipefail
          echo "=== intraday snapshot ==="

          INDEX_KEY="scoin_plus"
          CSV_PATH="docs/outputs/scoin_plus_intraday.csv"
          OUT_JSON="docs/outputs/scoin_plus_stats.json"
          OUT_TEXT="docs/outputs/scoin_plus_post_intraday.txt"
          OUT_PNG="docs/outputs/scoin_plus_intraday.png"

          SESSION_START="09:00"
          SESSION_END="15:30"
          DAY_ANCHOR="09:00"
          BASIS="prev_close"
          VALUE_TYPE="percent"

          python scripts/make_intraday_post.py \
            --index-key "$INDEX_KEY" \
            --csv "$CSV_PATH" \
            --out-json "$OUT_JSON" \
            --out-text "$OUT_TEXT" \
            --snapshot-png "$OUT_PNG" \
            --session-start "$SESSION_START" \
            --session-end "$SESSION_END" \
            --day-anchor "$DAY_ANCHOR" \
            --basis "$BASIS"

      - name: Upload artifacts (for debug)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scoin_plus_debug
          path: docs/outputs/

      - name: Commit outputs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/scoin_plus_*
          if ! git diff --cached --quiet; then
            git commit -m "chore(intraday): update scoin_plus (snapshot & post)"
            git push
          else
            echo "No changes to commit."
          fi
