name: Generate long-term charts (S-COIN+ 7d/1m/1y)

on:
  schedule:
    - cron: '15 1 * * *'   # JST 10:15
  workflow_dispatch:

permissions: { contents: write }

concurrency:
  group: scoinp-long-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      INDEX_KEY: scoin_plus
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt

      - name: Generate long-term charts (level)
        run: |
          python scripts/long_charts.py
          ls -lah "$OUT_DIR" || true
          date -u +"%Y-%m-%dT%H:%M:%SZ" > "$OUT_DIR/_last_run.txt"

      - name: Commit PNGs if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_DIR/scoin_plus_7d.png" "$OUT_DIR/scoin_plus_1m.png" "$OUT_DIR/scoin_plus_1y.png" "$OUT_DIR/_last_run.txt"
          if git diff --cached --quiet; then
            echo "no changes"
          else
            git commit -m "chore(scoin_plus): update long-term charts (7d/1m/1y)"
            git push
          fi
