name: S-COIN+ • intraday snapshot (JST 09:00–15:30)

on:
  workflow_dispatch:
    inputs:
      session_start:
        description: "Session start (HH:MM JST)"
        required: true
        default: "09:00"
      session_end:
        description: "Session end (HH:MM JST)"
        required: true
        default: "15:30"
      day_anchor:
        description: "Day anchor time for labeling (HH:MM JST)"
        required: true
        default: "09:00"
      basis:
        description: "Return basis label (e.g., open@09:00)"
        required: true
        default: "open@09:00"

permissions:
  contents: write

concurrency:
  group: scoin-plus-intraday-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify scripts & inputs exist
        run: |
          test -f scripts/make_intraday_post.py || (echo "Missing scripts/make_intraday_post.py" && exit 2)
          test -f docs/outputs/scoin_plus_intraday.csv || (echo "Missing docs/outputs/scoin_plus_intraday.csv" && exit 2)
          # 入力の簡易バリデーション（半角数字:コロン）
          [[ "${{ inputs.session_start }}" =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "session_start invalid"; exit 2)
          [[ "${{ inputs.session_end }}"   =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "session_end invalid";   exit 2)
          [[ "${{ inputs.day_anchor }}"    =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "day_anchor invalid";    exit 2)

      - name: Generate intraday post and snapshot
        env:
          INDEX_KEY: scoin_plus
          CSV: docs/outputs/scoin_plus_intraday.csv
          OUT_JSON: docs/outputs/scoin_plus_stats.json
          OUT_TEXT: docs/outputs/scoin_plus_post_intraday.txt
          SNAPSHOT_PNG: docs/outputs/scoin_plus_intraday.png
          SESSION_START: ${{ inputs.session_start }}  # 例: "09:00"
          SESSION_END:   ${{ inputs.session_end }}    # 例: "15:30"
          DAY_ANCHOR:    ${{ inputs.day_anchor }}     # 例: "09:00"
          BASIS:         ${{ inputs.basis }}          # 例: "open@09:00"
          VALUE_TYPE:    percent                      # ← 追加：CSVは％の系列として解釈
        run: |
          set -euo pipefail
          echo "=== intraday snapshot ==="
          echo "INDEX_KEY=${INDEX_KEY}"
          echo "SESSION_START=${SESSION_START}"
          echo "SESSION_END=${SESSION_END}"
          echo "DAY_ANCHOR=${DAY_ANCHOR}"
          echo "BASIS=${BASIS}"
          echo "VALUE_TYPE=${VALUE_TYPE}"

          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-json "${OUT_JSON}" \
            --out-text "${OUT_TEXT}" \
            --snapshot-png "${SNAPSHOT_PNG}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --value-type "${VALUE_TYPE}"

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scoin_plus_intraday_artifacts
          path: |
            docs/outputs/scoin_plus_intraday.png
            docs/outputs/scoin_plus_post_intraday.txt
            docs/outputs/scoin_plus_stats.json
          if-no-files-found: ignore
          retention-days: 3

      - name: Commit outputs if changed
        run: |
          set -e
          git config --global user.name  "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/outputs/scoin_plus_intraday.png \
                  docs/outputs/scoin_plus_post_intraday.txt \
                  docs/outputs/scoin_plus_stats.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(intraday): update scoin_plus (snapshot & post)"
            git push
          else
            echo "No output changes."
          fi
