name: S-COIN+ • intraday snapshot (JST 09:00–15:30)

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scoin_plus_intraday
  cancel-in-progress: false

env:
  INDEX_KEY: scoin_plus
  OUT_DIR: docs/outputs
  # セッション指定（JST）
  SESSION_START: "09:00"
  SESSION_END: "15:30"
  DAY_ANCHOR: "09:00"   # その日の起点（open@09:00 の基準に使う）

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python 3.11
       .uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify scripts exist
        run: |
          set -euxo pipefail
          test -f scripts/make_intraday_post.py || (echo "Missing scripts/make_intraday_post.py" && exit 2)

      - name: Generate intraday post and snapshot
        run: |
          set -euxo pipefail
          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${OUT_DIR}/${INDEX_KEY}_intraday.csv" \
            --out-json "${OUT_DIR}/${INDEX_KEY}_stats.json" \
            --out-text "${OUT_DIR}/${INDEX_KEY}_post_intraday.txt" \
            --snapshot-png "${OUT_DIR}/${INDEX_KEY}_intraday.png" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "open@09:00"

          echo "--- ${INDEX_KEY}_post_intraday.txt ---"
          sed -n '1,120p' "${OUT_DIR}/${INDEX_KEY}_post_intraday.txt" || true

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scoin-plus-intraday
          path: |
            docs/outputs/${{ env.INDEX_KEY }}_intraday.csv
            docs/outputs/${{ env.INDEX_KEY }}_intraday.png
            docs/outputs/${{ env.INDEX_KEY }}_post_intraday.txt
            docs/outputs/${{ env.INDEX_KEY }}_stats.json

      - name: Commit outputs if changed
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs/outputs
          if ! git diff --cached --quiet; then
            git commit -m "chore(intraday): update S-COIN+ snapshot+post (JST 09:00–15:30)"
            git push
          else
            echo "No changes to commit."
          fi
