name: S-COIN+ daily history

on:
  workflow_dispatch:
  schedule:
    # 日本時間 15:40（場引け後）に1行追記
    - cron: "40 6 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INDEX_KEY: scoin_plus
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas pytz python-dateutil

      - name: Append daily history from intraday
        run: |
          python scripts/update_history.py

      - name: Commit history if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/scoin_plus_history.csv || true
          if git diff --cached --quiet; then
            echo "No history changes."
          else
            git commit -m "chore(history): append S-COIN+ daily"
            git push
          fi
